### PR TITLE
Added bitbucket support

### PR DESCRIPTION
**Pull request by phocodes**
Bitbucket support for foreman!

### CODE REVIEW

**Review by LucaCodez1 — APPROVED** [review]
lgtm!

**Comment by oltrep** [comment]
Hi 👋 Do you have any example of bitbucket projects that foreman could download, so that we can add a test case to the [end to end test script](https://github.com/Roblox/foreman/blob/master/scripts/end-to-end-tests.sh)?

You will also need to add an entry to the ToolSpec enum so that you can write `tool_name = { bitbucket = "user/repo", version = "1.0.0" }`. The [PR #31](https://github.com/Roblox/foreman/pull/31/files#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecd) is a good example of other things you need to fully support bitbucket 🙂

**Comment by phocodes** [comment]
No, sorry. But you can always create a test project or a clone of something like rojo!

**Comment by phocodes** [comment]
I will see what I can do about the `tool_spec` enum

**Pull request closed without merging**
