### PR TITLE
Use group status to report exit code

### PR DESCRIPTION
**Pull request by oltrep**
A quick fix to correctly report exit code for long process runs.

### CODE REVIEW

**Review by ZoteTheMighty — COMMENTED** [review]
Is this testable with the new integration test structure?

**Comment by oltrep** [comment]
Not really, because I would need to install a real tool and call it to see if it returns the correct exit code. That would not test exactly the fix here, but more the behavior in general.

**Comment by ZoteTheMighty** [comment]
> Not really, because I would need to install a real tool and call it to see if it returns the correct exit code. That would not test exactly the fix here, but more the behavior in general.

Would it be possible to do this via a shell script that exits with an error or something else super simple, or would that be clumsy to set up?

**Review by ZoteTheMighty — APPROVED** [review]
Had one other suggestion, but if I'm missing something about what makes this awkward to test, the actual details look fine to me.

**Pull request merged**
